### PR TITLE
initial extmod fix

### PR DESCRIPTION
**Pull request by shakfu**
Initial changes to extmod.py to convert and compile trivial `def add(x, y): return x+y`

Compiles with lots of warnings but without errors and generates a working extension module. The caveat is that `add` somehow only takes `ints` but returns a float so there are more type fixes required in the next iteration.

### CODE REVIEW

**Comment by srepmub** [comment]
cool, thanks! =) will have a look and probably merge later today!

things are looking good for a python3-only release in a few weeks. all 220 tests now pass in the python3 branch (some stuff still commented out/to be added), and most of the examples in examples3 now compile (except for some relative imports and extmods of course).

**Comment by srepmub** [comment]
merged to the python3 branc.! thanks again! it works fine for me - no warnings or errors. and when I import it from python3 (checking that it does import the .so file) I can add numbers. with the following:

```def add(a, b):
    return a+b

if __name__ == '__main__':
    add(7, 8)
```

it accepts and returns ints for me.. 

what kind of warnings do you see?

**Comment by shakfu** [comment]
@srepmub The issue I saw was that the arguments had to be integers. they wouldn't accept float for example:

```python
In [7]: calc.add(10.0,2)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: 'float' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
Cell In [7], line 1
----> 1 calc.add(10.0,2)

SystemError: <built-in function add> returned a result with an exception set
```

Is there any way to allow for both integers and floats?

**Comment by srepmub** [comment]
if the function is compiled with floats, it should accept python integer objects, but there was a little problem where we need to use PyLong_Check instead of PyLong_AsLong, so I fixed that.  so this now works for me:

```
def add(a,b):
    return a+b

if __name__=='__main__':
    add(1.1,2,2)
```

when passing something else like strings, there is still something wrong with the exception handling.

**Comment by shakfu** [comment]
Ok thanks, that makes sense.

**Comment by shakfu** [comment]
@srepmub 

I figured out the string issue (in `str.cpp`), this works now properly:

```cpp
#ifdef __SS_BIND
str::str(PyObject *p) : hash(-1) {
    if(!PyUnicode_Check(p))
        throw new TypeError(new str("error in conversion to Shed Skin (string expected)"));

    __class__ = cl_str_;
    unit = __GC_STRING(PyUnicode_AsUTF8(p), PyUnicode_GET_SIZE(p));
```

**Comment by srepmub** [comment]
yeah, I can now add strings :) merged. thanks!

a next step might be to handle what happens when a wrong type of object is passed in. something wrong in exception handling I guess..

**Pull request closed without merging**
