### PR TITLE
tests2: improvement to extension testing

### PR DESCRIPTION
**Pull request by shakfu**
Happy holidays!

This PR introduces this option in the test runner:

```bash
cd tests2
./runtests.py -ce
```

This will build/run an executable and python extension test using cmake for each test in the directory. While this was possible previously using separate test runs. The above runs both types of tests in the same test run.

Also added extension testing for the default test runner via:

```bash
cd tests2
./runtests.py -e
```

Updated docs as as well.

### CODE REVIEW

**Comment by shakfu** [comment]
Last commit [53055a1](https://github.com/shedskin/shedskin/pull/326/commits/53055a10e9611b83283dbef1e6d7c5213654ea99) is a fix for the case of linking extensions in linux: linking in APPLE requires "-undefined dynamic_lookup" and on linux, this will cause a crash, so it's now enabled only for APPLE.

**Comment by shakfu** [comment]
Also some additional tests throughout (see [6961a75](https://github.com/shedskin/shedskin/pull/326/commits/6961a751ff7c7a794d5534e6bda74d6c6150a9b1))

**Comment by srepmub** [comment]
hi, thanks! meh, sorry, I'm still not completely recovered here, and under some stress from catching up with work and other things.. :package: 

I will try to have a look at fixing some of the warnings I'm seeing this weekend. and again hopefully start publicizing the release.

happy holidays to you too =)

**Comment by shakfu** [comment]
Hi Mark,

Thanks for the merge.

Hope you feel better and recover soon.

If I recall correctly, the last time I tested on linux, there was one recurring warning due to an unused `print` or `print_traceback` function in the tests.

**Pull request merged**
