### PR TITLE
python3

### PR DESCRIPTION
**Pull request by folkertvanheusden**

### CODE REVIEW

**Comment by srepmub** [comment]
thank you. yes it's going to be some work to make all tests and especially examples python3 compatible.. :P

**Comment by srepmub** [comment]
you probably want to include 'from __future__ import print_function' here, but I will add that here.

**Comment by folkertvanheusden** [comment]
I'm trying to do that but they all fail because of:

*** test: 206
*** SHED SKIN Python-to-C++ Compiler 0.9.5 *** -
Copyright 2005-2022 Mark Dufour and contributors; License GNU GPL version 3
(See LICENSE)

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/folkert/t/shedskin/shedskin/__main__.py", line 7, in <module>
    main()
  File "/home/folkert/t/shedskin/shedskin/__init__.py", line 176, in main
    start(gx, main_module_name)
  File "/home/folkert/t/shedskin/shedskin/__init__.py", line 165, in start
    analyze(gx, main_module_name)
  File "/home/folkert/t/shedskin/shedskin/infer.py", line 1387, in analyze
    gx.main_module = graph.parse_module(module_name, gx)
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 1705, in
parse_module
    mv.visit(module.ast)
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 141, in visit
    BaseNodeVisitor.visit(self, node, *args)
  File "/home/folkert/t/shedskin/shedskin/ast_utils.py", line 104, in visit
    return visitor(node, *args)
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 422, in
visit_Module
    self.visit(n)
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 141, in visit
    BaseNodeVisitor.visit(self, node, *args)
  File "/home/folkert/t/shedskin/shedskin/ast_utils.py", line 104, in visit
    return visitor(node, *args)
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 612, in
visit_ImportFrom
    module = self.import_modules(node.module, node, True)
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 585, in
import_modules
    module = self.import_module(subname, subname, node, fake)
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 592, in
import_module
    module = self.analyze_module(name, pseudonym, node, fake)
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 651, in
analyze_module
    module = parse_module(name, self.gx, getmv().module, node)
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 1705, in
parse_module
    mv.visit(module.ast)
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 141, in visit
    BaseNodeVisitor.visit(self, node, *args)
  File "/home/folkert/t/shedskin/shedskin/ast_utils.py", line 104, in visit
    return visitor(node, *args)
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 417, in
visit_Module
    self.visit(ClassNode(dummy, [], [], [Pass()]))
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 141, in visit
    BaseNodeVisitor.visit(self, node, *args)
  File "/home/folkert/t/shedskin/shedskin/ast_utils.py", line 104, in visit
    return visitor(node, *args)
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 1557, in
visit_ClassDef
    self.visit(parse_expr('def __i%s__(self, other): return
self.__%s__(other)' % (msg, msg)), newclass)
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 141, in visit
    BaseNodeVisitor.visit(self, node, *args)
  File "/home/folkert/t/shedskin/shedskin/ast_utils.py", line 104, in visit
    return visitor(node, *args)
  File "/home/folkert/t/shedskin/shedskin/graph.py", line 667, in
visit_FunctionDef
    func = Function(self.gx, node, parent, inherited_from, mv=getmv())
  File "/home/folkert/t/shedskin/shedskin/python.py", line 149, in __init__
    self.formals = extract_argnames(node.args)
  File "/home/folkert/t/shedskin/shedskin/ast_utils.py", line 56, in
extract_argnames
    argnames = [get_arg_name(arg) for arg in arg_struct.args]
  File "/home/folkert/t/shedskin/shedskin/ast_utils.py", line 56, in
<listcomp>
    argnames = [get_arg_name(arg) for arg in arg_struct.args]
  File "/home/folkert/t/shedskin/shedskin/ast_utils.py", line 52, in
get_arg_name
    assert isinstance(node, Name), "Expected Name got %s" % type(node)
AssertionError: Expected Name got <class 'ast.arg'>
*** failure: 206
Traceback (most recent call last):
  File "/home/folkert/t/shedskin/tests/./run.py", line 128, in
run_test_with_output
    assert execute('%s %s -m Makefile.%d %d' % (sys.executable, SS, test,
test)) == 0
AssertionError

**Comment by srepmub** [comment]
yes, we currently do not yet support the python3 'ast' module, which has differences from the 2.7 'ast' module, which was dramatically changed from the older 'compiler.ast' module.. sigh :P I just merged johan's 5000 line patch to at least move to the 2.7 ast. next is to start handling the changes in 3.x ast.. :P

**Comment by srepmub** [comment]
(in this case there is a large change in how calling arguments are represented in the ast)

**Pull request merged**
