### PR TITLE
use std::clamp in yiq_to_rgb instead of 6 if-statements

### PR DESCRIPTION
**Pull request by folkertvanheusden**

### CODE REVIEW

**Comment by srepmub** [comment]
nice, thanks!

**Comment by folkertvanheusden** [comment]
Oops, missing include.

I've pushed an update.

**Comment by Arkanosis** [comment]
> wait, I'm getting this error:
> error: ‘clamp’ is not a member of ‘std’

Different default C++ dialect maybe?

Try:

```sh
g++ -dM -E -x c++  /dev/null | grep -F __cplusplus
```

If you get anything below 17, it makes sense that you don't have `std::clamp`. So the minimum C++ version to compile would have to be raised to C++17.

**Comment by srepmub** [comment]
@folkert afraid you need to make a new PR, as this one is already merged? (I think)
@jeremie thanks! I'm on 2014. no idea if it makes sense to move to C++17..? it sounds like most platforms should support that by now, but no idea.. :P

**Pull request merged**
