### PR TITLE
basic GTP protocol handling

### PR DESCRIPTION
**Pull request by folkertvanheusden**
This is some code to make the shedskin go AI do the GTP protocol.
Note that I did not test if it still compiles with shedskin. That's because I noticed it plays invalid moves. E.g. when I set the boardsize to 3 then "play b a1", and then repeat some "genmove w", then after a while it will play a1 again.

### CODE REVIEW

**Comment by dstromberg** [comment]
3-3's can be pretty chaotic.  Are you sure there wasn't an "under the
stones" play?

**Comment by folkertvanheusden** [comment]
> 3-3's can be pretty chaotic. Are you sure there wasn't an "under the stones" play?

What is that?
What I saw was that it played a stone where already a stone was placed.

**Comment by dstromberg** [comment]
Here's a URL about "under the stones":
https://senseis.xmp.net/?UnderTheStones

It's probably all about 19x19, where it's uncommon.

I suspect it's more so on 3x3, though I almost exclusively play 19x19.

**Comment by folkertvanheusden** [comment]
Oh never mind: I made a bug (multiple even).
Now it plays fine.

@srepmub can you review the code?

**Comment by srepmub** [comment]
hehe, the change seems fine to me, and it compiles (after removing the traceback import).

note that this is a rather weak go player, from years before alphago. I never got around to implementing common pattern detection, which was really needed to become strong IIRC from the UCT paper.

**Pull request merged**
