### PR TITLE
Improve code readability/context with qualified naming scheme

### PR DESCRIPTION
**Pull request by shakfu**
@srepmub 

Here's a set of changes which you will probably not like but may lead to more people contributing to shedskin.

It's more verbose, but I think it will have the following benefits:
- more context and therefore makes the code easier to understand, namespace are a kind of documentation
- improved searchability (for `Name` vs `ast.Name` for example) makes the code easier to refactor
- no performance impact (lookups are cached anyway)
- qualified names creates space for further development trajectories (`cpp.generate_code` -> `rust.generate_code`)
- prevent name collisions (there was case of an imported function having the same name as a defined function which itself called the imported function, qualifying the imports made the confusion go away)
- etc..

### CODE REVIEW

**Comment by shakfu** [comment]
O, this also contained an initial effort to introduce mako templates but I thought the naming problem was more important so I shelved the mako code for the time being.

**Comment by srepmub** [comment]
hi shakeeb! thanks for this. I actually do think readability is very important, but may be a bit blind for it in my own projects haha.. :-) so yeah, I will see if I can merge your changes later today. I have to ask though, since extmod support is the only remaining thing for the next release - are you still looking into this? ;-) the most useful thing at the moment might be support for global variables, since that is blocking tests/e2, and also examples/fysphun.. btw do you also see strange crashes when an exception is thrown from the shedskin side? I'm looking at such a case, and so far haven't been able to figure out why..

**Comment by shakfu** [comment]
Hi Mark, good to hear extmod support is the only thing remaining for the next release. Looks like things have been moving along (-:

Thanks for the positive response to the PR. I personally believe it will help with other tasks, with onboarding new contributors, and improving a newcomer's learning curve. Further along, I see also see a need for more documentation (more / better docstrings) , and probably (nice to have at some point), taking advantage of python3 type hints and gradual typing.

With respect for the remaining todo's for extmod support, of course more testing is required. Unfortunately, I'm not in the habit of running all the tests and all the examples as this usually takes too long. I wonder if introducing something like `pytest` could help and/or have full tests run as a GitHub workflow.

In any case, I will have a look at the extmod global variable issue (but unfortunately not much spare time this week). Feel free to jump in and solve any issue which seems obvious to you. I won't complain (-:

**Comment by srepmub** [comment]
actually, I thiink at some point the tests were run for each pull request.. I will have a look why this doesn't work at the moment.

I first want to understand why I'm getting these segmentation faults during exception handling. perhaps if you could have another look at the global variables in the next few days or so, and submit your changes (even if they aren't finished), I can fix this issue, then hammer a bit further on the extmod stuff.

**Pull request merged**
