### PR TITLE
https://github.com/shedskin/shedskin/issues/215

### PR DESCRIPTION
**Pull request by folkertvanheusden**
Replaced murmur/etc by std::hash()

### CODE REVIEW

**Comment by srepmub** [comment]
oof! =) would it be possible to show some benchmarking??

**Comment by srepmub** [comment]
str hashing is kinda important in python, so a little comparison would be nice. if you don't feel like it (does the thumbs up mean that? :P), I can do that too.

also we should remove the -s/--strhash option with this.

**Comment by srepmub** [comment]
oh wait we still have the cpython-like hashing otherwise.. which may not even be compatible with cpython anymore. not sure if we want to keep that.

**Comment by srepmub** [comment]
interesting, thanks! ok I will test this a bit and probably merge shortly.

**Comment by Arkanosis** [comment]
> oh wait we still have the cpython-like hashing otherwise.. which may not even be compatible with cpython anymore. not sure if we want to keep that.

FWIW, CPython's implementation [is currently based on SipHash](https://github.com/python/cpython/blob/main/Python/pyhash.c) and the cpython-like hashing of shedskin doesn't look similar at all. SipHash is designed to be more resistant to collision attacks than Murmur, but it's also slower.

**Comment by folkertvanheusden** [comment]
Apparently they're synonyms:
https://cplusplus.com/reference/string/string/c_str/

**Comment by srepmub** [comment]
I guess, but 'data' sounds nicer to me if it's not zero-terminated.. not that important though ;-)

**Pull request merged**
