### PR TITLE
ruff safe fixes

### PR DESCRIPTION
**Pull request by shakfu**
I ran ruff --fix *./**/.py in the root of shedskin which applies safe fixes (like remove removing an unused import) and also fixed some undefined variables in `shedskin/cpp.py`. There remain a bunch of undefined variables in `shedskin/lib`: but I haven't fixed as they may be builtins:

```bash
array.py:81:16: F821 Undefined name `__iter`
bisect.py:9:5: F821 Undefined name `__cmp`
bisect.py:18:5: F821 Undefined name `__cmp`
collections.py:3:13: F821 Undefined name `pyiter`
collections.py:42:16: F821 Undefined name `__iter`
collections.py:145:16: F821 Undefined name `__iter`
csv.py:20:16: F821 Undefined name `__iter`
csv.py:45:16: F821 Undefined name `__iter`
datetime.py:85:22: F821 Undefined name `self`
datetime.py:92:20: F821 Undefined name `self`
glob.py:5:12: F821 Undefined name `__iter`
heapq.py:7:5: F821 Undefined name `__cmp`
heapq.py:14:5: F821 Undefined name `__cmp`
heapq.py:18:5: F821 Undefined name `__cmp`
heapq.py:22:5: F821 Undefined name `__cmp`
heapq.py:27:5: F821 Undefined name `__cmp`
heapq.py:32:5: F821 Undefined name `__cmp`
heapq.py:38:5: F821 Undefined name `__cmp`
io.py:4:14: F821 Undefined name `file_binary`
os/__init__.py:127:18: F821 Undefined name `file`
os/__init__.py:284:14: F821 Undefined name `file`
os/__init__.py:284:31: F821 Undefined name `file`
os/__init__.py:287:14: F821 Undefined name `file`
os/__init__.py:287:31: F821 Undefined name `file`
os/__init__.py:287:48: F821 Undefined name `file`
os/__init__.py:290:14: F821 Undefined name `file`
os/__init__.py:290:31: F821 Undefined name `file`
os/__init__.py:341:12: F821 Undefined name `file`
os/__init__.py:446:12: F821 Undefined name `file`
re.py:74:16: F821 Undefined name `__iter`
re.py:103:12: F821 Undefined name `__iter`
socket.py:49:16: F821 Undefined name `file`
sys.py:6:25: F821 Undefined name `file`
sys.py:6:40: F821 Undefined name `file`
sys.py:6:56: F821 Undefined name `file`
```

### CODE REVIEW

**Comment by srepmub** [comment]
hey, thanks! yeah the builtin .py files don't actually need to run correctly, as they are just there for type inference. we could fix the issues with some import statements I guess, but let's look at the other files first..

**Comment by srepmub** [comment]
btw note that 'all checks have passed' doesn't mean too much, as I think the exit code of 'shedskin test' is 0 even on failure. I still test changes manually, and intended to look into this for the next release perhaps.

**Comment by shakfu** [comment]
Sure no problem. Thanks!

**Comment by srepmub** [comment]
merged the examples/ changes. let's leave shedskin/lib for later. I suggest we can close this issue.

**Pull request closed without merging**
