### PR TITLE
Add ContextManager support to mmap

### PR DESCRIPTION
**Pull request by humhue**
I'm not used to writing C++, but this seems to work fine.

### CODE REVIEW

**Comment by srepmub** [comment]
looks good, thanks! =) bonus points if you feel like adding a basic test to shedskin/tests/test_mod_mmap/test_mod_mmap.py.

I don't think it was really necessary to add __enter__ and __exit__ methods to the .py model, right? although they could be used explicitly I guess.. :P (we currently don't define them for class file in lib/builtin.py).

**Comment by srepmub** [comment]
btw should I add 'Humhue' to the contributor list or your real name perhaps?

**Comment by humhue** [comment]
Yeah, to have the with statement working there's no need to edit the .py (because that's translated internally in C++).
I'd personally like the builtin modules in Shed Skin to map as closest as possible the real python API.
In this case, it's not particularly helpful, but I somewhat like the idea of being able to call a certain object initializator and deconstructor directly. It's fine if you don't feel the same about this, but we should stick to one for consistency, and well, in cpython those methods are callable directly.

If you want to, I can add the two methods to builtin.py or remove them from mmap.py.
I'll try to write a basic test as well.

Regarding the name to use, "Humhue" will do just fine.
Thanks a lot.

**Comment by srepmub** [comment]
no, I agree it's nicer to have these methods available.. :) so feel free to add them elsewhere. note that there are two file classes, one for binary and one for text mode. having nicer base classes here and there is a another area of improvement.

**Pull request merged**
