### PR TITLE
Fixed and added tests, added enter and exit methods for open

### PR DESCRIPTION
**Pull request by humhue**
All tests now run fine

### CODE REVIEW

**Comment by srepmub** [comment]
very nice, thank you! =)

did you manage to get your test program working yet?

**Comment by srepmub** [comment]
is there anything else that bugs you when using shedskin and/or you would like to work on? :)

**Comment by humhue** [comment]
Yep I got that source working almost immediately, even if I couldn't use the with statement with a mmap before. I gradually started optimizing the code reaching a 12x performance improvement (starting with a 4x performance improvement).

There are a lot of things I'd like to see implemented, especially something like lifetime analysis of variables, but I don't know enough about it to do that.

I think instead something like inlining functions would be way easier to implement to solve something like tuple packing/unpacking? Maybe with numba like decorators?

I'm also interested in implementing other python modules to extend Shed Skin's functionality, I'd like to have the threading module working, some zip module (gzip) and a GUI library like wxWidgets in a wxPython fashion

**Comment by srepmub** [comment]
a lifetime/escape analysis is not super hard I think. we just need a visitor class that tracks the flow of variable assignment/passing and draw some conclusions.. we can also start simple here and handle increasingly complex cases. if you are interested, just google a bit for 'escape analysis'.

the hard part seems to be the C++ side. how do we elegantly implement stack allocation (given that we are now using Boehm GC objects), also without making generated code ugly..

inlining could help in the particular case of returning and immediately unpacking tuples, but we could also add a hack for this that would work without inlining. the challenge is more in finding a general solution to many such problems I think.. inlining seems more appropriate for the C++ compiler to do.

threading is probably not going to be easy to support, as shedskin is not thread-safe in many places and that would require a substantial effort probably..

gzip might be nice, but GUI libraries are probably better used via 'shedskin -e'. so you compile only a part of your program, and the rest can still use any python library such as gzip or wxWidgets.

note that there are several example programs that use a GUI library this way, and even multiprocessing.

**Comment by humhue** [comment]
Escape analysis should eventually get implemented. I'll look into it.

I'm really interested in Shed Skin as a standalone executable generator, but I'm not that interested in generating extension with it.
I'd like to be able to build complex programs with Shed Skin only, and distribute a simple binary.

The threading module would be very useful, but it's probably the hardest to implement as well.
I think implementing certain modules shouldn't be that difficult? Couldn't we just rework the C/C++ sources of many modules and use them via a python interface?

**Comment by srepmub** [comment]
it really depends on the module. some should be easy, some rather hard, or even impossible because of type inference constraints.

note that for some modules, we added support to shedskin by compiling a pure python version of the module using shedskin itself.

**Pull request merged**
