### PR TITLE
Add str::c_str so that we can remove all instances of unit

### PR DESCRIPTION
**Pull request by tomspur**
This way one could finally multiple inherit from the string std class and a
smart pointer. At least we are independent of the interface pointing to the
implementation.

### CODE REVIEW

**Comment by fahhem** [comment]
There's a compiler error here: https://travis-ci.org/shedskin/shedskin/jobs/70730020#L561

Can you make unit protected to ensure it's not being used anywhere? Or is it used for other things?

**Comment by tomspur** [comment]
Thanks for looking into this.
It is still used for a lot of other things, I'll try to get to in this PR. I'm unsure if it will make any difference speedwise right now, but with the recent added [benchmarks](http://shedskin.github.io/benchmarks/) it should be measurable  at least :)

**Comment by stuaxo** [comment]
Looks like the unit tests pass https://travis-ci.org/shedskin/shedskin/builds/80715680

**Comment by fahhem** [comment]
Looks good to me, merging!

**Pull request merged**
