### PR TITLE
Simplify complex numbers parsing and avoid static dependency on PCRE for this

### PR DESCRIPTION
**Pull request by pfalcon**
Based on the discussion in https://github.com/shedskin/shedskin/issues/228#issuecomment-460085330 . Individual commits of the PR have more detailed descriptions.

### CODE REVIEW

**Comment by pfalcon** [comment]
CI now passes.

**Comment by pfalcon** [comment]
Ok, added more testcases to 183.py, including introducing negative testcases, and caught a few unhandled cases in my initial patch, now fixed.

**Comment by pfalcon** [comment]
@Arkanosis: Any comments?

**Comment by srepmub** [comment]
thanks for your pull request!

I will try to comment within a few days at least.

**Comment by srepmub** [comment]
looks very nice, thanks again!

**Comment by pfalcon** [comment]
Thanks for merging!

**Pull request merged**
