### PR TITLE
[WIP] Porting to python3

### PR DESCRIPTION
**Pull request by tomspur**
This branch contains some fixes and initial work to port to python3.

### CODE REVIEW

**Comment by zanellia** [comment]
Is anyone still working on porting Shed Skin to Python 3?

**Comment by tomspur** [comment]
The biggest open issue is to port it from the compiler module, which would require a rewrite of big parts of shedskin. I don't think anyone is currently working on it though

[1] https://docs.python.org/2/library/compiler.html

**Comment by pfalcon** [comment]
FYI, I've ported Python2 "compiler" package to Python3: http://github.com/pfalcon/python-compiler .

But I think it make sense to formulate the issue better. What "compiler" does is generating bytecode from AST. I don't think that Shedskin needs that. Quickly looking at the code, what it has is stuff like:

~~~
from compiler.ast import Const, AssTuple, AssList, From, Add, Stmt, AssAttr, \
    Keyword, AssName, CallFunc, Slice, Getattr, Dict, Subscript, \
    Function as FunctionNode, Return, Class as ClassNode, Name, List, Discard, Sliceobj, Tuple
from compiler.visitor import ASTVisitor
~~~

So, what Shedskin appears to be interested in is exactly the AST. And initially Python AST was exactly prototyped within the scope of "compiler" package. But that was in 2000. Since then, AST construction and manipulation was factored out into "ast" module: https://docs.python.org/2/library/ast.html .

So, per my understanding, that would be the mission statement:

* **Upgrade Shedskin from historical `compiler.ast` module to the mainline `ast` module.**

Initially, that should be done yet within Python2 scope, and that will pave the road for Python3 (sup)port.

For example, my work on porting "compiler" to Python3 exactly largely construed switching to the `ast` module (plus of course updating generated bytecode sequences).

It would be nice to get a confirmation from the maintainers whether that makes sense. Thanks.

**Comment by Arkanosis** [comment]
> FYI, I've ported Python2 "compiler" package to Python3: [http://github.com/pfalcon/python-compiler](https://github.com/pfalcon/python-compiler) .

Whoa, that's great :)

> what Shedskin appears to be interested in is exactly the AST. […]
> So, per my understanding, that would be the mission statement:
> * **Upgrade Shedskin from historical `compiler.ast` module to the mainline `ast` module.**

Sounds correct to me, with a few additions that are in the new `ast` module as well.

Grepping through the master branch, here's what I get:
```console
$ sed -n 's/from compiler\.\([^ ]*\) import /\1 /p' shedskin/**/*.py
ast Const, AssTuple, AssList, Assign, AugAssign, \
ast Const, AssTuple, AssList, From, Add, Stmt, AssAttr, \
visitor ASTVisitor
ast Const, AssTuple, AssList, From, Add, ListCompFor, \
visitor ASTVisitor
ast Const, Node, AssAttr, Keyword, CallFunc, Getattr, Dict, List, Tuple, ListComp, Not, Compare, Name
ast AssTuple, AssList, List, Tuple, CallFunc, Name, \
ast CallFunc, Name
$  sed -n 's/from compiler import //p' shedskin/**/*.py
walk
parse
```

⇒ so, we mostly use stuff from `compiler.ast`, as well as `compiler.visitor.ASTVisitor`, `compiler.walk` and `compiler.parse`, all of which are in the new `ast` module.

Good catch!

**Comment by pfalcon** [comment]
Nice, thanks for confirming. So, if somebody will be interested to play with such an upgrade, hopefully they comment here. I myself would be, but I'm only getting acquainted with Shedskin, and have a bunch of other projects in the pipeline, so it may take a while to get to it...

**Comment by srepmub** [comment]
nice work guys. I'm have to say I'm not as opposed to Python3 anymore as I was 10 years ago, having ported lots of code at work in the meantime.. :-)

note that running Shedskin with python3 is only one of several changes needed. type inference changes (meh) and unicode string support spring to mind, but I'm sure there will be many more things to tackle..

anything we can do while still (only) supporting python2 sounds great, eg moving to 'ast'. IIRC we also already support 'from __future__ import print_function'..

**Comment by srepmub** [comment]
I will look at thomas' commits shortly in any case, to see what we can already merge from those.

**Comment by srepmub** [comment]
thomas, I just looked at this branch (sorry for the slight delay.. :S), and made a separate PR for one commit which doesn't seem to be in master yet (slightly cumbersome because of rewriting history recently). please let me know if I missed something.

**Comment by srepmub** [comment]
played a little bit with this, and it doesn't seem straightforward to use ast instead of compiler.ast (on python2). it's not just that node types have been renamed, but there seem to have been quite some structural changes as well.

**Comment by srepmub** [comment]
another option might be a compatibility layer (potentially useful for others), converting new-style ast's to old-style ones, which could be gradually minimized until everything is directly on 'ast'.

**Comment by pfalcon** [comment]
> it doesn't seem straightforward to use ast instead of compiler.ast (on python2). it's not just that node types have been renamed, but there seem to have been quite some structural changes as well.

Yes, that's definitely the case. But it's not like AST structure is completely different. There're some patterns. One meta-pattern is that where compiler.ast had concept of "node children", and getChildNodes() accessor, the `ast` module uses "uniform" approach of node properties (attributes), and it's just some properties contains lists of subnodes. E.g., for FunctionDef (former Function), node.body is a list of statement nodes.

Then all binary operators were collected under BinOp, etc. As I mentioned, I went thru the conversion for the `compiler` package itself (for https://github.com/pfalcon/python-compiler), and it's not surmountable.

But it's definitely "mid-term" goal. I'd start with low-hanging fruit of converting Shedskin to "modern Python2", like print function, using bytes() where possible, etc.

**Comment by DevJohan** [comment]
After reading the discussion here I've done an initial port of Shedskin to use the ast module and opened a PR(#261 )

**Comment by pfalcon** [comment]
@DevJohan: That's cool, thanks! I hope it'll catch attention of the maintainers, I hope to look into it too. (But it looks like a massive patch, and reviewing/merging such is always hard ;-) ).

**Comment by DevJohan** [comment]
@pfalcon: I know it's a huge monolithic patch but I don't see any alternative in this case :smiley:. Hopefully this will code will help towards running Shedskin under Python3 in the future.

**Comment by srepmub** [comment]
apologies again for missing the rest of this discussion! I actually went through a covid burnout, around this time and lost track of the project :P will make sure to at least be following the discussions from now on.

**Comment by srepmub** [comment]
thanks all for your comments! let's close this issue and create separate ones for different aspects of moving to python3. I will start by adding a few that I know of.. :-)

**Pull request closed without merging**
