### PR TITLE
Update mmap.cpp

### PR DESCRIPTION
**Pull request by folkertvanheusden**
Please use the MAP_FAILED define and not -1 directly.

### CODE REVIEW

**Comment by srepmub** [comment]
unfortunately the tests are not red at the moment when they fail.. :P but this currently fails with:

```
/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/shedskin/lib/mmap.cpp: In member function ‘void* __mmap__::mmap::__init__(int, __shedskin__::__ss_int, __shedskin__::__ss_int, __shedskin__::__ss_int, __shedskin__::__ss_int, __shedskin__::__ss_int)’:
/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/shedskin/lib/mmap.cpp:163:5: error: expected ‘,’ or ‘;’ before ‘if’
  163 |     if (temp == MAP_FAILED)
      |     ^~
/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/shedskin/lib/mmap.cpp: In member function ‘void* __mmap__::mmap::resize(__shedskin__::__ss_int)’:
/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/shedskin/lib/mmap.cpp:218:57: error: expected ‘,’ or ‘;’ before ‘)’ token
  218 |                                     size_t(new_size), 0));
      |                                                         ^
/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/shedskin/lib/mmap.cpp:224:15: error: invalid conversion from ‘void*’ to ‘__mmap__::mmap::iterator’ {aka ‘char*’} [-fpermissive]
  224 |     m_begin = temp;
      |               ^~~~
      |               |
      |               void*
```

could you update the PR pretty-please.. :-)

**Comment by srepmub** [comment]
thanks! still seems to have a compilation issue, but will check on my system.

**Comment by folkertvanheusden** [comment]
strange?
tried g++ shedskin/lib/mmap.cpp

**Comment by srepmub** [comment]
well it's working now.. see my latest change.

**Pull request merged**
