### PR TITLE
Update math.cpp

### PR DESCRIPTION
**Pull request by folkertvanheusden**
Use constants from cmath (untested)

### CODE REVIEW

**Comment by srepmub** [comment]
nooo:

```
/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/shedskin/lib/math.cpp:8:22: error: conflicting declaration ‘constexpr const __ss_float __math__::e’
    8 | constexpr __ss_float e = M_E, pi = M_PI;
      |                      ^
In file included from /opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/shedskin/lib/math.cpp:4:
/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/shedskin/lib/math.hpp:13:19: note: previous declaration as ‘__shedskin__::__ss_float __math__::e’
   13 | extern __ss_float e;
      |                   ^
/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/shedskin/lib/math.cpp:8:31: error: conflicting declaration ‘constexpr const __ss_float __math__::pi’
    8 | constexpr __ss_float e = M_E, pi = M_PI;
      |                               ^~
In file included from /opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/shedskin/lib/math.cpp:4:
/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/site-packages/shedskin/lib/math.hpp:12:19: note: previous declaration as ‘__shedskin__::__ss_float __math__::pi’
   12 | extern __ss_float pi;
      |          
```

**Comment by folkertvanheusden** [comment]
Fixed

**Comment by folkertvanheusden** [comment]
Did I add #include <math.h> ?

**Comment by srepmub** [comment]
yes, math.hpp:

#include <math.h>

math.cpp:

#include <cmath>

**Pull request merged**
