### PR TITLE
tests2 progress

### PR DESCRIPTION
**Pull request by shakfu**
Further work on `tests2` folder: key thing now is that all tests in `tests2` pass for `pytest`, and (cmake) cpp-exe, and cpp-ext (python extension) cases.

To test using `pytest`:

```bash
cd tests2
pytest
```

To test using cmake for cpp-exe:

```bash
cd tests2
./runtests.py -c
```

To test using cmake for cpp-ext (python extension):

```bash
cd tests2
./runtests.py -ce
```

The next iteration should be to add windows support for the cmake test-runner and also to test both cpp-exe and cpp-ext cases in the same test run instead of in separate test runs.

### CODE REVIEW

**Comment by srepmub** [comment]
nice work! ;-) let me give that a try..

**Comment by shakfu** [comment]
@srepmub Thanks!

> getting some compiler warnings for runtest -c

Could you share them? Are they linux specific? I've been working off of os x and tested just once on linux (it worked), but no testing whatsoever on windows

> would be really nice later on if we could run 'pytest' directly to run all/specific tests I think..? (pytest should be flexible enough for this)

I've looked into this. `pytest` is already very useful since it helps to test 2 out of 3 of the cases: pure python and the api of the compiled python extension. However, it cannot help on the compiled cpp-exe case. Even the current translation of the python `assert` to the cpp `ASSERT` here is not helpful if it fails since you only get an `AssertionError` without any other helpful messages.

One solution to this is to include a cpp single-header testing framework (such as [utest.h](https://github.com/sheredom/utest.h) or [doctest](https://github.com/doctest/doctest)) with `shedskin` and then have a switch in the command-line to indicate generation is for testing and then `asserts` are translated to the testing framework idiom instead of plain `ASSERT`.

**Comment by srepmub** [comment]
```
In file included from /home/srepmub/shedskin/tests2/../../shedskin/shedskin/lib/builtin.hpp:1280,
                 from /home/srepmub/shedskin/tests2/build/test_assign.cpp:1:
/home/srepmub/shedskin/tests2/../../shedskin/shedskin/lib/builtin/exception.hpp:12:13: warning: ‘void __shedskin__::print_traceback(FILE*)’ defined but not used [-Wunused-function]
   12 | static void print_traceback(FILE *out)
      |             ^~~~~~~~~~~~~~~
[  1%] Building CXX object CMakeFiles/test_assign.dir/home/srepmub/shedskin/shedskin/lib/builtin.cpp.o
In file included from /home/srepmub/shedskin/shedskin/lib/builtin.cpp:166:
/home/srepmub/shedskin/shedskin/lib/builtin/bytes.cpp: In member function ‘__shedskin__::__ss_int __shedskin__::bytes::count(__shedskin__::__ss_int, __shedskin__::__ss_int, __shedskin__::__ss_int)’:
/home/srepmub/shedskin/shedskin/lib/builtin/bytes.cpp:488:22: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘__shedskin__::__ss_int’ {aka ‘int’} [-Wsign-compare]
  488 |     for(i = start; i < end; i++) {
      |                    ~~^~~~~
In file included from /home/srepmub/shedskin/shedskin/lib/builtin.cpp:169:
/home/srepmub/shedskin/shedskin/lib/builtin/format.cpp: In instantiation of ‘__shedskin__::str* __shedskin__::do_asprintf(const char*, T, __shedskin__::pyobj*, __shedskin__::pyobj*) [with T = int]’:
/home/srepmub/shedskin/shedskin/lib/builtin/format.cpp:171:26:   required from here
/home/srepmub/shedskin/shedskin/lib/builtin/format.cpp:67:9: warning: variable ‘x’ set but not used [-Wunused-but-set-variable]
   67 |     int x;
      |         ^
/home/srepmub/shedskin/shedskin/lib/builtin/format.cpp: In instantiation of ‘__shedskin__::str* __shedskin__::do_asprintf(const char*, T, __shedskin__::pyobj*, __shedskin__::pyobj*) [with T = double]’:
/home/srepmub/shedskin/shedskin/lib/builtin/format.cpp:178:26:   required from here
/home/srepmub/shedskin/shedskin/lib/builtin/format.cpp:67:9: warning: variable ‘x’ set but not used [-Wunused-but-set-variable]
In file included from /home/srepmub/shedskin/shedskin/lib/builtin.hpp:1280,
                 from /home/srepmub/shedskin/shedskin/lib/builtin.cpp:3:
/home/srepmub/shedskin/shedskin/lib/builtin/exception.hpp: At global scope:
/home/srepmub/shedskin/shedskin/lib/builtin/exception.hpp:12:13: warning: ‘void __shedskin__::print_traceback(FILE*)’ defined but not used [-Wunused-function]
   12 | static void print_traceback(FILE *out)
      |             ^~~~~~~~~~~~~~~
```

**Comment by shakfu** [comment]
I don' think these warning are related to cmake. Need to have another warning removal session.

**Pull request merged**
