### PR TITLE
Replace print statements with logging and a real progressbar

### PR DESCRIPTION
**Pull request by fahhem**
No more print statements to print debugging statements, warnings, or errors. This cleans up printing a bit and it allows us to redirect these to separate files as wanted. Setup for replacing the codegen printing with jinja2 templates.

### CODE REVIEW

**Comment by fahhem** [comment]
https://github.com/shedskin/shedskin/pull/209/files#diff-ec05ac3ef13044de572f8385a77dc50eR41

The import is progressbar because it's just a fork of google's unmaintained python-progressbar library

**Comment by tomspur** [comment]
Could you please have a look at #208, as we have some conflicts now in `__init__.py`? Maybe that one could also get merged it then...

**Comment by fahhem** [comment]
Regarding #208, I'm looking at it now. I've got the output from logging in this branch for error_tests, except I'm getting a Traceback due to an actual error in test 10. It seems like there are too many global variables in shedskin at the moment to replace subprocesses with shedskin.main calls.

**Comment by tomspur** [comment]
Strange, it seems to work fine over here and on travis as we get the same two failures on all branches currently. The tests 201 and 202 fail there...

**Comment by fahhem** [comment]
Travis doesn't check the error_tests (run.py -x)

**Comment by fahhem** [comment]
With both setup.py and requirements.txt pointing to progressbar2, I'd say it should work. But if you want, I can make the import only happen if -n is not set. Otherwise, I'll merge this in later today.

**Comment by tomspur** [comment]
I think importing it only if -n is not set would make sense indeed.

I try to get travis build also the extension and error tests directly in master as that shouldn't conflict with this PR...

**Pull request merged**
